### ISSUE TITLE
moko安装怎么总是报错

### ISSUE THREAD

**Issue by ivernaloo** [abruzzi/qipa#1]
Building native extensions.  This could take a while...
ERROR:  Error installing moko:
        ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb
```

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from extconf.rb:1:in `<main>'

Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.3 for inspection.
Results logged to /var/l

**Comment by ivernaloo** [comment]
windows,ubuntu下都报这个错误
